package org.drc.vat.appmanager;

import java.text.SimpleDateFormat;
import java.util.Date;
import org.testng.asserts.SoftAssert;

public class StringDeclare {
	public static String category;
	public static String lastyearrevenue;
	public static String taxoffice;
	public static String addressline1;
	public static String addressline2;
	public static String province;
	public static String city;
	public static String zipcode;
	public static String mobilenumber;
	public static String businessname;
	public static String baddressline1;
	public static String baddressline2;
	public static String bprovince;
	public static String bcity;
	public static String bmobilenumber;
	public static String email;
	public String times = new SimpleDateFormat("HHmmss").format(new Date());
	public SoftAssert sassert = new SoftAssert();
	public static String StoreCaseID;
	public static String StoreCaseID_NITVA;
	public static String StoreRecoveryAmount;
	public static String StoteTA;
	public static String StoteIA;
	public static String StoteDA;
	public static String StoteDP;
	public static String StoteSIA;
	public static String StoteNoIA;
	public static String StoteIF;
	public static String StoteNIA;
	public static String StoreNID_1;
	public static String StoteAS;
	public static String StoreIA;
	public static String StrorePA_Case_ID;
	public static String StrorePA_Agreement_ID;
	public static String Store_CreationDate;
	public static String StoreTaxPayerName;
	public static String StoreTaxPayerAddress;
	public static String StoreAssignedTo;
	public static String ITitle;
	public static Float Total_VC;
	public static Float TotalD;
	public static Float VDC;
	public static Float VRC;
	public static Float SDC;
	public static Float PCC;
	public static Float FPPS;
	public static Float NetVAT;
	public static String Total_NetVAT;
	public static String Total_VATcredit;
	public static String Total_Refund;
	public static String Total_Forward;
	public static String Total_Procurement;
	public static String VAT3Party;
	public static String Total_Pay;
	public static String VAT_Collected_DG;
	public static String VAT_Collected_DS;
	public static String VAT_Collected_DSI;
	public static String VAT_Collected_DGI;
	public static String VAT_Collected_FPP;
	public static String StoreSysRelated;
	public static Float ODG;
	public static Float DS11;
	public static Float DS21;
	public static Float Export;
	public static Float Exempt;
	public static Float Nontaxable;
	public static Float DGI1;
	public static Float DSI1;
	public static Float FPP1;
	public static Float TotalA;
	public static Float TotalG;
	public static Float TotalR;
	public static Float TotalO;
	public static String DGI;
	public static String DSI;
	public static String FPP;
	public static String DG;
	public static String Username;
	public static String vendoremail;
	public static String NITVA;
	public static String NitvaNo;
	public static String NITVA_Number;
	public static String collectofficername;
	public String BaseCurr;
	public String BaseCurrName;
	public String BaseCurrCheck;
	public String StoreCurrency;
	public String pendingamount;
	public static int recordNo = 0;
	public static boolean isRecordSet = true;
	public static String debtcaseid;
	public static String totalDebtAmount = null;
	public String Acaction = null;
	public static int records = 1;
	public String createdDaterec = null;
	public String performOfficer = null;
	public String approvedOfficer = null;
	public String txpayer = null;
	public String nitvano = null;
	public String createdDate = null;
	public String source = null;
	public String reason = null;
	public String comment = null;
	public String olddate = null;
	public String oldperiod = null;
	public String oldpartic = null;
	public String ovatliab = null;
	public String oltfee = null;
	public String oint = null;
	public String openal = null;
	public String adjperiod = null;
	public String adjcharge = null;
	public String adjvatliab = null;
	public String adjltfee = null;
	public String adjpenal = null;
	public String cdate = null;
	public String Tvatliab = null;
	public String Ttfee = null;
	public String Tpenal = null;
	// Objection and Appeal
	public String CaseMObjectionid = null;
	public String assessmentId = null;
	public String CaseDebtId = null;
	public int apendingtoapprorec = 0;
}
