Feature: The user can see the status for the application of NITVA number whether it is Approved,Rejected or needs additional clarification

  @Reject
  Scenario Outline: The user can see the status as "Rejected" for the application of NITVA number when the officer Rejects the application
    Given the officer has Rejected the form and The User is on Dashboard After Successfully login from taxpayer portal "<username>" "<password>"
    Then User must see the application Status as Rejected
    And again applies for VAT Registration

    Examples: 
      | Test Case ID                          | username              | password   |
      | TC_DRC_ATC_UserRegistration_Status_26 | reject@mailinator.com | reject@123 |

  @AdditionalClarification
  Scenario Outline: The user can edit the form after after the officer asks for some clarification with proper comment
    Given the officer Ask for additional clarification in the form and The User is on Dashboard After Successfully login from taxpayer portal"<userName>""<password>"
    When user clicks on edit button for clarifying form details
    Then the user is redirected to review and submit page
    And Edits the clarifications details needed respectively "<gedit>" "<Category>""<Subcategory>""<LLPyn>""<NIF>""<NIFdate>""<BFullName>""<IFullName>""<TrainingName>""<BusinessType>""<n_coi>""<incdate>""<BusinessStartDAte>""<CompanySize>""<LastYearREvenue>"
    And may edit reg address of business"<Badd1>""<Badd2>""<Bprovince>""<Bcity>""<Bmobileno>""<BZipcode>"
    And may edit details of Promoters "<PromoterYN>" "<Pname>""<Padd1>""<Padd2>""<Pprovince>""<PCity>""<Pzipcode>""<Pmail>""<Pmobileno>"
    And May edit Authorized Signatory"<AuthYN>""<Atitle>""<Aname>""<Aemail>""<Amobileno>"
    And Can Edit Bank Details "<bedit>""<acno>""<acname>""<bankName>""<branch>"
    And clicks on continue
    And Clicks on Reply button enters comment "<Comment>" along with the documents"<DocType>""<docdesc>""<FilePath>"
    And clicks on I agree
    And again Submits the form to DGI officer for review

    Examples: 
      | Test Case ID                          | userName                   | password | gedit | Category            | Subcategory         | LLPyn | NIF | NIFdate    | BFullName  | IFullName | TrainingName | BusinessType | n_coi | incdate    | BusinessStartDAte | CompanySize | LastYearREvenue | Badd1       | Badd2  | Bprovince | Bcity | BZipcode | Bmobileno   | PromoterYN | Pname | Padd1  | Padd2 | Pprovince | PCity | Pzipcode  | Pmail          | Pmobileno | AuthYN | Atitle | Aname | Aemail          | Amobileno  | bedit | acno        | acname     | bankName    | branch  | DocType            | docdesc   | FilePath                   | Comment                                         |
      | TC_DRC_ATC_UserRegistration_Status_16 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_17 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |       | 2018-07-01 |                   | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_18 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              |              |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_19 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_20 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_21 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_22 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_23 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_24 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_25 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_26 | testrejected1@o3enzyme.com | 12345678 | N     | Legal Entity        | Incorporated Bodies |       |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_33 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_34 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_35 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_36 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Incorporated Bodies | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_37 | testrejected1@o3enzyme.com | 12345678 | N     | Legal Entity        | Incorporated Bodies |       |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_38 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_39 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_40 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_41 | testrejected1@o3enzyme.com | 12345678 | Y     | Incorporated Bodies | NonCoroporates      | Yes   |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_42 | testrejected1@o3enzyme.com | 12345678 | N     | Incorporated Bodies | NonCoroporates      |       |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_43 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_44 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_45 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_46 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | NonCoroporates      | No    |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_47 | testrejected1@o3enzyme.com | 12345678 | N     | Legal Entity        | NonCoroporates      | No    |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_48 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Government Entity   |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_49 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Government Entity   |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_50 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Government Entity   |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_51 | testrejected1@o3enzyme.com | 12345678 | Y     | Legal Entity        | Government Entity   |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_52 | testrejected1@o3enzyme.com | 12345678 | N     | Legal Entity        | Government Entity   |       |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_53 | testrejected1@o3enzyme.com | 12345678 | Y     | Natual Person       | Individual          |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_54 | testrejected1@o3enzyme.com | 12345678 | Y     | Natual Person       | Individual          |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_55 | testrejected1@o3enzyme.com | 12345678 | Y     | Natual Person       | Individual          |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_56 | testrejected1@o3enzyme.com | 12345678 | Y     | Natual Person       | Individual          |       |     | 08/02/2018 | Mining Duo |           |              | Mining       |     3 | 2018-07-01 | 2018-07-01        | Large Scale |    132456487897 | Dc Chambers | valsad | Bas-Uele  | Aketi |   134564 | 97789456321 | Y          | Test  | valsad | Valsd | Bas-Uele  | Ango  | 465489787 | test@gmail.com | 987654123 | Y      | CA     | Bosco | bosco@gmail.com | 9876543210 | y     | 34905734654 | Mining Duo | Advans Bank | Branch4 | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |
      | TC_DRC_ATC_UserRegistration_Status_57 | testrejected1@o3enzyme.com | 12345678 | N     | Natual Person       | Individual          |       |     |            |            |           |              |              |       |            |                   |             |                 |             |        |           |       |          |             | N          |       |        |       |           |       |           |                |           | N      |        |       |                 |            | y     |             |            |             |         | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | completed with the updation as per th e comment |

  @Approve
  Scenario Outline: The user can see the status as "Aprroved" for the application of NITVA number when the officer Approves the application
    Given The DGI officer has approved for NITVA and The User is on Dashboard After Successfully login from taxpayer portal
    Then User must see the application Status as Approved   on the Dashboard
    And Views the NITVA Certificate
     Examples: 
      | Test Case ID  |
      |TC_DRC_ATC_UserRegistration_Status_58  |                       

  @comment&document
  Scenario Outline: The user can clear or delete the uploaded document
    Given the officer Ask for additional clarification in the form and The User is on Dashboard After Successfully login from taxpayer portal
    When user clicks on edit button for clarifying form details
    Then the user is redirected to review and submit page
    And Must Reply with the comment "<comment>" along with the documents
    And Adds and removes the document "<doctype>" "<docdesc>" "<docpath>""<Add>""<doctype2>""<docdesc2>""<docpath2>""<validation message>""<Condition>"
    And clicks on I agree
    And again Submits the form to DGI officer for review

    Examples: 
      | Test Case ID                          | username                   | password | comment                                                                                                                                                                                                                                                     | doctype1           | docdesc1    | docpath                    | Add | doctype2           | docdesc2  | docpath2                   | validation message                                                                                                        | Condition                                                 |
      | TC_DRC_ATC_UserRegistration_Status_07 | testrejected1@o3enzyme.com | 12345678 | Update in comment Section                                                                                                                                                                                                                                   | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.png | y   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_08 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | Please enter comment and upload the respective file                                                                       |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_09 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | Please enter comment and upload the respective file                                                                       | Cancelbutton                                              |
      | TC_DRC_ATC_UserRegistration_Status_10 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             | Bank Account Proof | doc_desc9   |                            | n   |                    |           |                            |                                                                                                                           | ImageSize equal                                           |
      | TC_DRC_ATC_UserRegistration_Status_11 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | Maximum size limit is 2MB                                                                                                 | Image size greater                                        |
      | TC_DRC_ATC_UserRegistration_Status_12 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            |                                                                                                                           | Image Size less than                                      |
      | TC_DRC_ATC_UserRegistration_Status_13 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | please select/upload valid file                                                                                           | Other document and greater size                           |
      | TC_DRC_ATC_UserRegistration_Status_14 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | please select/upload valid file                                                                                           | Other Document                                            |
      | TC_DRC_ATC_UserRegistration_Status_01 | testrejected1@o3enzyme.com | 12345678 | Natural Person                                                                                                                                                                                                                                              |                    | Onlydocumet |                            | n   |                    |           |                            | I have attached a Affidavit which represent that the  person in the address proof and the application are the same person |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_02 | testrejected1@o3enzyme.com | 12345678 | Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.  |                    |             |                            | n   |                    |           |                            |                                                                                                                           |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_03 | testrejected1@o3enzyme.com | 12345678 | Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium   |                    |             |                            | n   |                    |           |                            |                                                                                                                           | please enter comment description less than 250 characters |
      | TC_DRC_ATC_UserRegistration_Status_04 | testrejected1@o3enzyme.com | 12345678 | Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium.q |                    |             |                            | n   |                    |           |                            |                                                                                                                           |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_05 | testrejected1@o3enzyme.com | 12345678 | Lorem ipsu                                                                                                                                                                                                                                                  |                    |             |                            | n   |                    |           |                            |                                                                                                                           |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_06 | testrejected1@o3enzyme.com | 12345678 | Lorem ips                                                                                                                                                                                                                                                   |                    |             |                            | n   |                    |           |                            |                                                                                                                           |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_15 | testrejected1@o3enzyme.com | 12345678 | Lorem ips                                                                                                                                                                                                                                                   |                    |             |                            | n   |                    |           |                            |                                                                                                                           |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_27 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             |                    |             |                            | n   |                    |           |                            | please reply with related comment first                                                                                   |                                                           |
      | TC_DRC_ATC_UserRegistration_Status_28 | testrejected1@o3enzyme.com | 12345678 | Update in comment Section                                                                                                                                                                                                                                   | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.png | y   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        | remove                                                    |
      | TC_DRC_ATC_UserRegistration_Status_29 | testrejected1@o3enzyme.com | 12345678 | Update in comment Section                                                                                                                                                                                                                                   | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.jpg | y   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        | other Image                                               |
      | TC_DRC_ATC_UserRegistration_Status_30 | testrejected1@o3enzyme.com | 12345678 | Update in comment Section                                                                                                                                                                                                                                   | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.gif | n   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        | image                                                     |
      | TC_DRC_ATC_UserRegistration_Status_31 | testrejected1@o3enzyme.com | 12345678 | Update in comment Section                                                                                                                                                                                                                                   | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.png | n   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        | file                                                      |
      | TC_DRC_ATC_UserRegistration_Status_32 | testrejected1@o3enzyme.com | 12345678 |                                                                                                                                                                                                                                                             | Bank Account Proof | doc_desc9   | F:\\documents\\Capture.png | n   | Bank Account Proof | doc_desc9 | F:\\documents\\Capture.png | Please select Document Description                                                                                        | close                                                     |

@SaveDraft
  Scenario Outline: Save Fraft on Required Documents page
    Given The DGI officer raised for additional clarification from and  The User is on Required Documnets page after 
    Then User must Upload document in bank ac proof
    Then Logout from the application 
    Then Replace with another document and click on save draft and logout
    Then delete the uploaded banck ac prrof
    Then Logout from the application 
    And See the document remains intact
     Examples: 
      | Test Case ID  |
      |TC_DRC_ATC_UserRegistration_Status_59  |   